kind: pipeline
name: default

steps:
- name: build docker image
  image: plugins/docker
  settings:
    repo: docker.funzt-halt.net/alerts-panel
    tags: latest
    cache_from: "docker.funzt-halt.net/alerts-panel:latest"
