---
kind: pipeline
name: default

steps:
- name: build docker image
  image: plugins/docker
  settings:
    repo: docker.funzt-halt.net/alerts-panel
    tags: latest
---
kind: signature
hmac: 9fb7725a83151a0fccbfa4444252f8e5e48d66e751851cecbc9175e74683b91b

...
